-- AdFit 콘솔 세션 쿠키 보관용. 관리자 화면에서 갱신해 재배포 없이 자동 수익 조회를 복구한다.
-- 한 행만 두고 쓴다. 조회는 id 역순 첫 행을 읽으므로 행이 늘어도 마지막 값이 이긴다.
CREATE TABLE IF NOT EXISTS adfit_session_cookies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    cookie_value VARCHAR(4096) NOT NULL
);
