CREATE TABLE IF NOT EXISTS adfit_daily_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    report_date DATE NOT NULL,
    ad_unit VARCHAR(30) NOT NULL,
    revenue NUMERIC(16, 2) NOT NULL CHECK (revenue >= 0),
    cost NUMERIC(16, 2) NOT NULL CHECK (cost >= 0),
    cost_basis VARCHAR(30) NOT NULL,
    CONSTRAINT uk_adfit_daily_date_unit UNIQUE (report_date, ad_unit)
);
