-- 관리자가 발급하는 테스트 계정(username/password) 로컬 로그인을 위한 테이블
CREATE TABLE IF NOT EXISTS user_local_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_user_local_accounts_username UNIQUE (username),
    CONSTRAINT uk_user_local_accounts_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_local_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
